name: donationUtil
version: '1.0'
main: dev.gotiger.donationUtil.DonationUtil
api-version: '1.16'
load: STARTUP
commands:
  du:
    description: donationUtil 플러그인 명령어
    usage: /<command> [arguments]
  보호권:
    description: 인벤 보호권 확인 명령어
    usage: /<command> [player]
    aliases: invp